### PR TITLE
Handling case insensitive exclude labels

### LINKED ISSUE #726: Case insensitive labels
It would be nice if the list elements for `--exclude-labels` etc. were compared case-insensitively. So I could say `--exclude-labels invalid` and issues marked `Invalid` also get picked up and excluded. Currently all the defaults contain both lowercase and capitalized versions so it wouldn't change any default behaviour, either.

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
This PR close #726 handling the `exclude_labels` option as a case insensitive option.

It does so downcasing every string in the issue, as well as the ones added to the flag.

The `default_options` function at [parser.rb#237](https://github.com/github-changelog-generator/github-changelog-generator/blob/master/lib/github_changelog_generator/parser.rb#L237) could be simplified, but I'm waiting for feedback to do so.

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Hi @rafaeelaudibert ! Thanks for your PR.

Can you please add some test cases?

thanks!

**Comment by rafaeelaudibert** [comment]
Sure, will try to add it tonight (or in the next 24 hours).

**Comment by rafaeelaudibert** [comment]
> Hi @rafaeelaudibert ! Thanks for your PR.
> 
> Can you please add some test cases?
> 
> thanks!

Added a comprehensive test, and updated the old ones to match this change!
I've also upgraded some test performance, as Rubocop was complaining at them.

**Comment by skywinder** [comment]
Looks good. Thanks, @rafaeelaudibert 
I think we can merge it! cc @ferrarimarco , please check if you have a time! 🙏

**Comment by ferrarimarco** [comment]
@rafaeelaudibert can you please squash the commits in a single one now that's almost ready?

It's going to be easier to review.

Thanks!

**Comment by rafaeelaudibert** [comment]
Hey guys! Thanks for the awesome comments. Squashed it, and ready for review/merge.

**Comment by olleolleolle** [comment]
@rafaeelaudibert Thanks for the improvement - there's been some code movement under the feet of this (nice!) PR.

Would you be able to rebase on master?

**Comment by rafaeelaudibert** [comment]
Looks like I fucked up while rebasing and lost the commit with the changes (should have read about rebase better, my bad).

I will try to redo it sometime during the week, sorry for the mistake.

**Comment by olleolleolle** [comment]
Perhaps there's a git reflog way of getting the changes back? Web search for reflog, might help! Holding my thumbs.

**Comment by ferrarimarco** [comment]
Don't worry, it's the first commit on this branch. Look in the "Files changed" tab in the PR to see what's really changing.

**Comment by ferrarimarco** [comment]
See https://github.com/github-changelog-generator/github-changelog-generator/pull/737/files

The important bit here, is that we *squash and merge*, not

**Pull request closed without merging**
