### PR TITLE
Optionally Print Issue and Pull Requests Body

### PR DESCRIPTION
**Pull request by ArtieReus**
This commit adds the possibility by configuration to enhance the issues and pull requests lines printed in the changelog with the first paragraph of body. Empty bodies will be ignore so that the default behaviour stays as it is.

The here proposed enhancement would look like this:

**Fixed bugs:**

- Error when trying to generate log for repo without tags [\#32](https://github.com/skywinder/Github-Changelog-Generator/issues/32)  
This is the body of the issue. It will just copy the first paragraph of the body.

**Merged pull requests:**

- PrettyPrint class is included using lowercase 'pp' [\#43](https://github.com/skywinder/Github-Changelog-Generator/pull/43) ([schwing](https://github.com/schwing))  
This is the body of the pull request. It will just copy the first paragraph of the body.

Having this pull request as an example this will be the difference adding "issue_line_body" in your configuration:

- Optionally Print Issue and Pull Requests Body [\#XX](https://github.com/skywinder/Github-Changelog-Generator/pull/XX) ([ArtieReus](https://github.com/ArtieReus))

- Optionally Print Issue and Pull Requests Body [\#XX](https://github.com/skywinder/Github-Changelog-Generator/pull/XX) ([ArtieReus](https://github.com/ArtieReus))  
This commit adds the possibility by configuration to enhance the issues and pull requests lines printed in the changelog with the first paragraph of body. Empty bodies will be ignore so that the default behaviour stays as it is.

### CODE REVIEW

**Comment by olleolleolle** [comment]
(This change is one of those that would be much simpler to do when we have custom templates instead - so that the user would pick what to output themselves, using that.)

**Comment by ArtieReus** [comment]
@lindydonna still waiting for any action over 1 month.  If you want to use it before it gets merged you can get it from my fork: https://github.com/ArtieReus/github-changelog-generator/tree/include_body_issue
It looks pretty nice, see changelog in one of my projects: https://github.com/sapcc/elektra/blob/master/CHANGELOG.md

**Comment by lindydonna** [comment]
@ArtieReus I tried to use it from your fork, but I'm running into strange problems with master trying to run on MacOS. Any ideas on https://github.com/skywinder/github-changelog-generator/issues/629? 

I ended up backporting your change to 1.4.3, but it's a horrible hack!

**Comment by ArtieReus** [comment]
Happy to hear that. Applied changes.

**Comment by ArtieReus** [comment]
Anything new on this PR

**Comment by skywinder** [comment]
Thanks, @ArtieReus 
Let's wait for the final decision of @olleolleolle , since he is a captain of that project for now 😉

**Comment by ArtieReus** [comment]
Merged master into the branch. Notice that I changed
Time.new(2017, 12, 4, 12).utc
to
Time.new(2017, 12, 4, 12, 0, 0, "+00:00").utc
in
spec/unit/generator/entry_spec.rb
just because in my time zone I was getting a different date.

Thx

**Comment by ferrarimarco** [comment]
Instead of merging new commits can you please just rebase you work on master? Thanks

**Comment by ArtieReus** [comment]
Done!

**Comment by olleolleolle** [comment]
I'll take this into master, now.

**Pull request merged**
