### PR TITLE
Get commits from release branch

### LINKED ISSUE #891: Different results when generating a CHANGELOG.md
### I have a problem with different results when generating the changelog of a project. 

As you can see on the screenshot generating the changelog has errors with the order of the pull requests in the releases sections. There was a deletion from one section, an addition to another.

Screenshot 2020-08-19 at 13 08 49

### I used next parameters:
My repo is private, I use GitHub API token.
`docker run -it --rm -v $pwd:/usr/local/src/your-app  ferrarimarco/github-changelog-generator --project=<project> --user=<user> --token=<token> --unreleased_label "Latest:" --release-branch master --no-issues --no-filter-by-milestone`

### Output:
```
Using these options:
:date_format=>"%Y-%m-%d"
:output=>"CHANGELOG.md"
:base=>"HISTORY.md"
:issues=>false
:add_issues_wo_labels=>true
:add_pr_wo_labels=>true
:pulls=>true
:filter_issues_by_milestone=>false
:author=>true
:unreleased=>true
:unreleased_label=>"Latest:"
:compare_link=>true
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "Duplicate", "Question", "Invalid", "Wontfix", "Meta: Exclude From Changelog"]
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]
:breaking_labels=>["backwards-incompatible", "Backwards incompatible", "breaking"]
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]
:bug_labels=>["bug", "Bug", "Type: Bug"]
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]
:removed_labels=>["removed", "Removed", "Type: Removed"]
:security_labels=>["security", "Security", "Type: Security"]
:configure_sections=>{}
:add_sections=>{}
:issue_line_labels=>[]
:max_issues=>nil
:simple_list=>false
:ssl_ca_file=>nil
:verbose=>true
:header=>"# Changelog"
:merge_prefix=>"**Merged pull requests:**"
:issue_prefix=>"**Closed issues:**"
:summary_prefix=>""
:breaking_prefix=>"**Breaking changes:**"
:enhancement_prefix=>"**Implemented enhancements:**"
:bug_prefix=>"**Fixed bugs:**"
:deprecated_prefix=>"**Deprecated:**"
:removed_prefix=>"**Removed:**"
:security_prefix=>"**Security fixes:**"
:http_cache=>true
:require=>[]
:project=>"hidden value"
:user=>"hidden value"
:token=>"hidden value"
:release_branch=>"master"

Found 68 tags
Fetching tags dates: 68/68
Sorting tags...
Received issues: 162
Pull Request count: 162
Filtered pull requests: 145
Fetching events for issues and PR: 145
Fetching closed dates for issues: 145/145
Fetching SHAs for tags: 68
Warning: PR 158 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 157 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 156 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 145/145
Generating entry...
Done!
Generated log placed in /usr/local/src/your-app/CHANGELOG.md
```

### Steps to reproduce:
- run `github-changelog-generator` (does not matter using docker or a binary file)
- git add . && git commit -m "1"
- then run again github-changelog-generator`
- git status

### In my case, the results are always different, commits jump from one section to another or disappears altogether.

### LINKED ISSUE #927: No merge sha found for PR * via the GitHub API (StandardError)
Hi,

Thanks for this amazing library.
I am facing the below issue on running the change-log generator command:

Logs:
...
Found 95 tags
Fetching tags dates: 95/95
Sorting tags...
Received issues: 512
Pull Request count: 504
Filtered pull requests: 408
Filtered issues: 8
Fetching events for issues and PR: 416
Fetching closed dates for issues: 416/416
Fetching SHAs for tags: 95
*/vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:88:in `block in associate_tagged_prs': No merge sha found for PR 57 via the GitHub API (StandardError)
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:70:in `reject'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:70:in `associate_tagged_prs'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:50:in `add_first_occurring_tag_to_prs'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:151:in `fetch_issues_and_pr'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:47:in `compound_changelog'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:35:in `run'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:5:in `<top (required)>'
	from */vendor/bundle/ruby/2.6.0/bin/github_changelog_generator:23:in `load'
	from */vendor/bundle/ruby/2.6.0/bin/github_changelog_generator:23:in `<main>'
Warning: PR 57 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found

Could you please help me in debugging this issue?

### LINKED ISSUE #971: Pull requests missing
**Describe the bug**

We recently noticed that in latest releases of our [Seldon Core](https://github.com/SeldonIO/seldon-core/) the `Merged pull requests` section is missing. 

**To Reproduce**

Full changelog with missing pull requests for releases 1.8 and 1.9 is [here](https://github.com/SeldonIO/seldon-core/blob/master/CHANGELOG.md). 

1. Clone seldon-core
2. Checkout master
3. Execute 
```
docker run --rm -it -v $(pwd):/work -w /work ruby bash -c 'gem install github_changelog_generator && bash'
    github_changelog_generator -u seldonio --token [github api token here to avoid limits] --project seldon-core
```
4. See lots of errors of form
```
Warning: PR 3222 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3217 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3211 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3209 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3205 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3203 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3200 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3193 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3191 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3188 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3183 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3172 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3171 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3166 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3163 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3160 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3159 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3155 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3153 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3152 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3151 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3147 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3142 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3141 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3135 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3134 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3123 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3118 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3117 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3116 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3110 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3104 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3101 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3099 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3095 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3094 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3093 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3092 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3090 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3089 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3088 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3086 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3085 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3083 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3082 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3081 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3078 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3076 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3074 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3060 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3055 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3048 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3044 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3014 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2959 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2955 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2920 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2917 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2895 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2742 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2740 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2270 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2268 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1795 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 659 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
```

**Expected behavior**

No errors and pull requests always included. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu 20.04
 - Browser [Chrome but N/A]
 - Version [20.04]

**Additional context**

### PR DESCRIPTION
**Pull request by pokey**
This issue should help with #971, #891 and #927, but looks like it might not completely address all cases seen by users

The issue is that the commits API endpoint on Github grabs the commits for the repository's default branch by default.  Thus, if the release branch is not the repository's default branch, we won't find any commits for the release branch

### CODE REVIEW

**Comment by olleolleolle** [comment]
Looks nice, did this change the test output? Or was that red before this change?

**Comment by pokey** [comment]
The failure on CI does look related to my change; will have a look today

**Comment by pokey** [comment]
Ok tests are green

**Review by olleolleolle — APPROVED** [review]
Right, this API usage update takes "configured release branch" into account.

Thanks for the update @pokey!

**Pull request merged**
